language: node_js
node_js: 
  - 16.17.1
  cache: npm
npm --version:
  - 8.15.0
before_install:
  - npm install codecov --save-dev
  install:
  - npm ci
deploy:
provider: pages
skip-cleanup: true
github-token: $GITHUB_TOKEN
on:
branch: main
